/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ru.javaroadmap.java-conventions")
}

dependencies {
    implementation("org.projectlombok:lombok:1.18.22")
}

group = "ru.javaroadmap.shared-dto"
description = "shared-dto"
