/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ru.javaroadmap.java-conventions")
}

dependencies {
    implementation(project(":shared-dto"))
    implementation(project(":stock"))
    implementation(project(":import"))
}

group = "ru.javaroadmap.report"
description = "report"
