/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ru.javaroadmap.java-conventions")
}

dependencies {
    implementation("org.glassfish:jakarta.el:4.0.1")
    implementation("org.mindrot:jbcrypt:0.4")
    implementation("org.springframework.boot:spring-boot-starter-web:2.6.4")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:2.6.4")
    implementation("org.springframework.boot:spring-boot-starter-security:2.6.4")
    implementation("org.postgresql:postgresql:42.3.6")
    implementation("org.springframework.boot:spring-boot-starter-validation:2.6.4")
    implementation("org.springframework.boot:spring-boot-starter-actuator:2.6.4")
    implementation("org.projectlombok:lombok:1.18.22")
    implementation("org.springframework.kafka:spring-kafka:2.8.3")
    implementation("com.auth0:java-jwt:4.0.0")
    implementation("org.mapstruct:mapstruct:1.4.2.Final")
    implementation(project(":shared-dto"))
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.6.4")
}

group = "ru.javaroadmap.stock"
description = "stock"
