/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ru.javaroadmap.java-conventions")
}

dependencies {
    implementation(project(":shared-dto"))
}

group = "ru.javaroadmap.stock"
description = "stock"
