#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<-EOSQL
    CREATE USER $STOCK_DB_USER WITH PASSWORD '$STOCK_DB_PASSWORD';
    CREATE DATABASE $STOCK_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $STOCK_DB_USER TO $STOCK_DB_USER;
    CREATE DATABASE $STOCK_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $STOCK_DB_NAME TO $STOCK_DB_USER;
EOSQL
